### PR TITLE
Add kotlin dsl

### PR DESCRIPTION
**Pull request by StefMa**
* Updated the Guide to Kotlin DSL
* Updated the README to mach other guides
* Updated Gradle to latest release

The Kotlin test passes. But because we check here for an "runtime exception" it passes but not with the same error as the Groovy DSL.
If I change the `then` to something different, the Kotlin DSL error looks like this:
<details>

```
* What went wrong:
Script compilation errors:

  Line 28:         create("greetingsPlugin") {       
                   ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                       public inline fun <reified U : Any> PolymorphicDomainObjectContainer<in ???>.create(name: String): ??? defined in org.gradle.kotlin.dsl
                       public inline fun <reified U : Any> PolymorphicDomainObjectContainer<in ???>.create(name: String, crossinline configuration: ???.() -> Unit): ??? defined in org.gradle.kotlin.dsl
                       public fun DependencyHandler.create(group: String, name: String, version: String? = ..., configuration: String? = ..., classifier: String? = ..., ext: String? = ...): ExternalModuleDependency defined in org.gradle.kotlin.dsl
                       public inline fun <reified T : Task> TaskContainer.create(name: String, vararg arguments: Any): ??? defined in org.gradle.kotlin.dsl

  Line 30:             displayName = "<short displayable name for plugin>"       
                       ^ 'val Build_gradle.displayName: String' can't be called in this context by implicit receiver. Use the explicit one if necessary

  Line 30:             displayName = "<short displayable name for plugin>"       
                       ^ Val cannot be reassigned

  Line 33:             version = "1.2"       
                       ^ 'var Build_gradle.version: Any' can't be called in this context by implicit receiver. Use the explicit one if necessary

4 errors
```

</details>

So the exception of the Groovy Version is different than the one of the Kotlin DSL.
According to IntelliJ it should work.
The `PublishBundleExtension` has a `plugin` method:
bildschirmfoto 2018-08-08 um 08 44 14
Don't know what kind of issues that is. cc @eskatos

### CODE REVIEW

**Comment by eriwen** [comment]
Look at that nice issue. Details/summary and everything. Nice @StefMa!

**Comment by marcphilipp** [comment]
Indeed! Thanks, @StefMa! 👍

**Comment by bamboo** [comment]
I'm afraid this won't work with Gradle Kotlin DSL 1.0-RC1. The string invoke syntax for container no longer means `maybeCreate` but `named`.

**Comment by StefMa** [comment]
I investigated a little bit and found out that if I use `this.plugins{}` it works without issues (or better: with the same issue like the Groovy DSL ).

So maybe the Kotlin DSL get confused with the "name" of the method.
Because the `plugins{}` block is also used for applying plugins. So maybe it is confused which `plugins{}` block I want to call. The `plugins{}` "method" from the `PublishBundleExtension` or the "top level" `plugins{}` block of the Gradle script (the one from `KotlinBuildScript#plugins`).

**Comment by marcphilipp** [comment]
But why does it work for the `gradlePlugins` extension?

**Comment by StefMa** [comment]
Great question 👆 
Maybe its not the issue I described above but the `plugins` overload in the `PluginBundleExtension`.. :
bildschirmfoto 2018-08-09 um 08 41 00
The `GradlePluginDevelopmentExtension` (from the java-gradle-plugin plugin (well 😂)) have only one:
bildschirmfoto 2018-08-09 um 08 42 32

**Comment by marcphilipp** [comment]
Sounds like a reasonable explanation. `(plugin)` with `create("")` or `maybeCreate("")` should work, though.

**Comment by tomdcc** [comment]
That's correct. See the Kotlin examples on https://plugins.gradle.org/docs/publish-plugin - need to put `(plugins) {` rather than `plugins {` given the collision. This worked for Groovy but not Kotlin. The plugin bundle DSL predates the Kotlin DSL by quite a bit, but we might want to consider renaming the block to avoid the collision.

**Comment by marcphilipp** [comment]
@tomdcc Can't we just remove the `plugins(Closure)` method? Groovy DSL code would continue to work. Downstream plugins, if any, might break but we could mark the change as potentially breaking.

@StefMa FYI I've submitted #7 to make the Kotlin DSL sample work with Gradle 4.9 and 4.10.

**Pull request merged**
